//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DejaBrew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string CustFirstName { get; set; }
        public string CusLastName { get; set; }
        public int CartID { get; set; }
        public string UserUName { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
        public virtual User User { get; set; }
    }
}
