//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DejaBrew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.CartItems = new HashSet<CartItem>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public decimal CartTotal { get; set; }
    
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
